# Generated by Django 4.2.9 on 2024-02-07 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_product_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="Category",
            new_name="category",
        ),
    ]
