# Generated by Django 4.2.9 on 2024-02-14 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_rename_addres1_profile_address1_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
