# Generated by Django 4.2.9 on 2024-02-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="commenter_name",
            field=models.CharField(max_length=200),
        ),
    ]
